### ISSUE TITLE
Why do you choose Spring Native for your app

### ISSUE THREAD

**Issue by HelloTo4x** [itsgauravsaxena/spring-native-graalvm-mvn#1]
Hi, i am reading your project, but i have a question, why do u choose Spring Native for your app instead of Quarkus of other framework for build with GraalVM. Can u tell me the pros and cons of Spring Native ? When should we use it instead of other framewoks ?

**Comment by itsgauravsaxena** [comment]
I was only experimenting with spring native. I chose it because I work in spring eco-system and most of our apps are built with springboot and other spring components so it goes hand in hand. Even though there are blogs about 'Quarkus for Spring'. I believe Quarkus would have also been great choice and there are many blogs comparing the two. 
That is not exactly the answer to your question but please reach out if you have more questions.
